<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BaseController;
use App\Http\Controllers\BlogAdminController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\KeranjangController;
use App\Http\Controllers\PesananAdminController;
use App\Http\Controllers\PesananController;
use App\Http\Controllers\ProdukAdminController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WishlistController;
use Illuminate\Support\Facades\Route;

Route::get('', [BaseController::class, 'index']);
Route::get('/tentang', [BaseController::class, 'tentang']);
Route::get('/hubungi', [BaseController::class, 'hubungi']);
Route::get('/blog', [BlogController::class, 'index']); 
Route::get('/blog/{blog:slug}', [BlogController::class, 'show']);
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'Autentikasi']);
    Route::get('/register', [AuthController::class, 'register']);
    Route::get('/register/otp', [AuthController::class, 'otpView']);
    Route::get('/lupa-password', [AuthController::class, 'lupaPassword']);
    Route::post('/lupa-password', [ResetPasswordController::class, 'sendResetToken']);
    Route::get('/reset-password', [ResetPasswordController::class, 'index']);
    Route::post('/reset-password', [ResetPasswordController::class, 'updatePassword']);
    Route::post('/register/otp', [AuthController::class, 'cekOtp']);
    Route::post('/register', [AuthController::class, 'RegisterStore']);
    Route::get('/kirim-otp/{verificationcode}', [AuthController::class, 'kirim_ulang_otp'])->where('verificationcode', '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::post('/cek-bukti-bayar/{pesanan:no_pesanan}', [AdminController::class, 'cekBuktiBayar']);
    Route::get('/admin/dashboard', [AdminController::class, 'index']);
    Route::get('/admin/daftar-user', [AdminController::class, 'daftarUser']);
    Route::post('/admin/hapus-user/{user:username}', [AdminController::class, 'hapusUser']);
    Route::get('/admin/profil', [AdminController::class, 'profil']);
    Route::get('/admin/blog-view', [BlogAdminController::class, 'indexBlog']);
    Route::get('/admin/blog-tambah', [BlogAdminController::class, 'tambahViewBlog']);
    Route::post('/admin/blog-tambah', [BlogAdminController::class, 'tambahBlog']);
    Route::get('/admin/blog-edit/{blog:slug}', [BlogAdminController::class, 'editViewBlog']);
    Route::post('/admin/blog-edit/{blog:slug}', [BlogAdminController::class, 'editBlog']);
    Route::post('/admin/blog-hapus', [BlogAdminController::class, 'hapusBlog']);
    Route::get('/admin/blog-kategori-view', [BlogAdminController::class, 'indexKategori']);
    Route::get('/admin/blog-kategori-tambah', [BlogAdminController::class, 'tambahViewKategori']);
    Route::post('/admin/blog-kategori-tambah', [BlogAdminController::class, 'tambahKategori']);
    Route::get('/admin/blog-kategori-edit/{blogkategori:slug}', [BlogAdminController::class, 'editViewKategori']);
    Route::post('/admin/blog-kategori-edit/{blogkategori:slug}', [BlogAdminController::class, 'editKategori']);
    Route::post('/admin/blog-kategori-hapus', [BlogAdminController::class, 'hapusKategori']);
    Route::get('/admin/produk-view', [ProdukAdminController::class, 'indexProduk']);
    Route::get('/admin/storage-link', [ProdukAdminController::class, 'linkStorage']);
    Route::get('/admin/produk-tambah', [ProdukAdminController::class, 'tambahViewproduk']);
    Route::post('/admin/produk-tambah', [ProdukAdminController::class, 'tambahproduk']);
    Route::get('/admin/produk-edit/{produk:slug}', [ProdukAdminController::class, 'editViewProduk']);
    Route::post('/admin/produk-edit/{produk:slug}', [ProdukAdminController::class, 'editProduk']);
    Route::post('/admin/produk-hapus', [ProdukAdminController::class, 'hapusProduk']);
    Route::post('/admin/tambah-diskon', [ProdukAdminController::class, 'diskon']);
    Route::get('/admin/produk-kategori-view', [ProdukAdminController::class, 'indexKategori']);
    Route::get('/admin/produk-kategori-tambah', [ProdukAdminController::class, 'tambahViewKategori']);
    Route::post('/admin/produk-kategori-tambah', [ProdukAdminController::class, 'tambahKategori']);
    Route::get('/admin/produk-kategori-edit/{produkkategori:slug}', [ProdukAdminController::class, 'editViewKategori']);
    Route::post('/admin/produk-kategori-edit/{produkkategori:slug}', [ProdukAdminController::class, 'editKategori']);
    Route::post('/admin/produk-kategori-hapus', [ProdukAdminController::class, 'hapusKategori']);
    Route::get('/admin/produk-warna-view', [ProdukAdminController::class, 'indexWarna']);
    Route::get('/admin/produk-warna-tambah', [ProdukAdminController::class, 'tambahViewWarna']);
    Route::post('/admin/produk-warna-tambah', [ProdukAdminController::class, 'tambahWarna']);
    Route::get('/admin/produk-warna-edit/{produkwarna:slug}', [ProdukAdminController::class, 'editViewWarna']);
    Route::post('/admin/produk-warna-edit/{produkwarna:slug}', [ProdukAdminController::class, 'editWarna']);
    Route::post('/admin/produk-warna-hapus', [ProdukAdminController::class, 'hapusWarna']);
    Route::get('/admin/produk-ukuran-view', [ProdukAdminController::class, 'indexUkuran']);
    Route::get('/admin/produk-ukuran-tambah', [ProdukAdminController::class, 'tambahViewUkuran']);
    Route::post('/admin/produk-ukuran-tambah', [ProdukAdminController::class, 'tambahUkuran']);
    Route::get('/admin/produk-ukuran-edit/{produkukuran:slug}', [ProdukAdminController::class, 'editViewUkuran']);
    Route::post('/admin/produk-ukuran-edit/{produkukuran:slug}', [ProdukAdminController::class, 'editUkuran']);
    Route::post('/admin/produk-ukuran-hapus', [ProdukAdminController::class, 'hapusUkuran']);
    Route::get('/admin/pesanan', [PesananAdminController::class, 'index']);
    Route::post('/kirim-pesanan/{pesanan:no_pesanan}', [PesananController::class, 'kirimPesanan']);
});
Route::middleware(['auth', 'user', 'cek'])->group(function () {
    Route::get('/keranjang/proses-pesanan', [PesananController::class, 'prosesPesanan']);
    Route::post('/keranjang/cek-out', [PesananController::class, 'cekOutPesanan']);
});
Route::middleware(['auth', 'user'])->group(function () {
    Route::get('/keranjang/{username}', [KeranjangController::class, 'index']);
    Route::post('/tambah-ke-keranjang', [KeranjangController::class, 'tambahKeKeranjang']);
    Route::post('/upload-bukti-bayar/{pesanan:no_pesanan}', [UserController::class, 'uploadBuktiBayar']);
    Route::post('/action-keranjang', [KeranjangController::class, 'updateDeleteKeranjang']);
    Route::get('/wishlist/{username}', [WishlistController::class, 'index']);
    Route::post('/wishlist/tambah-wishlist/{produk:slug}', [WishlistController::class, 'tambahWishlist']);
    Route::post('/wishlist/hapus-wishlist/{produk:slug}', [WishlistController::class, 'hapusWishlist']);
    Route::get('/pesanan/{username}', [PesananController::class, 'index']);
    Route::get('/pesanan/{username}/{pesanan:no_pesanan}', [PesananController::class, 'show']);
    Route::get('/profil/{username}', [UserController::class, 'index']);
});
Route::middleware('auth')->group(function () {
    Route::post('/logout',[AuthController::class,'logout']);
    Route::get('/shop/{produk:slug}', [ProdukController::class, 'show']);
    Route::get('/shop', [ProdukController::class, 'index']);
    Route::get('/{produk:slug}', [KeranjangController::class, 'keranjangModal']);
    Route::post('/batalkan-pesanan/{pesanan:no_pesanan}', [PesananController::class, 'batalkanPesanan']);
    Route::post('/selesaikan-pesanan/{pesanan:no_pesanan}', [PesananController::class, 'selesaiPesanan']);
    Route::post('/profil/{username}/update-alamat', [UserController::class, 'updateAlamat']);
    Route::post('/profil/{username}/update-profil', [UserController::class, 'updateProfile']);
});
